/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musiccataloguemasy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.regex.Matcher; 
import java.util.regex.Pattern;

/**
 *
 * @author Nancy Merciline
 */
public class Loginswap extends javax.swing.JFrame {

    /**
     * Creates new form Loginswap
     */
    MySQLConnect myc;
    public Loginswap() {
        initComponents();
        myc = new MySQLConnect();
        setLocationRelativeTo(null);
    }
    
        boolean isValid(String email) { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
        boolean passValid(String password){
            String PASSWORD_REGEX = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$";
            Pattern  PASSWORD_PATTERN =Pattern.compile(PASSWORD_REGEX);
            if (PASSWORD_PATTERN.matcher(password).matches()){
                return true;
            }else{
                return false;
            }
       }
        
        boolean phValid(String phNo){
            String regex = "(0/91)?[7-9][0-9]{9}";
            if(phNo.matches(regex)){
                return true;
            }else{
                return false;
            }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FirstName_var = new javax.swing.JTextField();
        Lastname_var = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        User_id_var = new javax.swing.JTextField();
        Email_var = new javax.swing.JTextField();
        PhoneNo_var = new javax.swing.JTextField();
        Country_var = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        submit_signup_btn = new javax.swing.JButton();
        Confirmpassword_var = new javax.swing.JPasswordField();
        password_var = new javax.swing.JPasswordField();
        Gender_cb = new javax.swing.JComboBox<>();
        DOB_dc = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(31, 27, 36));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 83, 251));
        jLabel1.setText("Sign Up ");

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Birth:");

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");

        jLabel6.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");

        FirstName_var.setBackground(new java.awt.Color(255, 255, 255));
        FirstName_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_varActionPerformed(evt);
            }
        });

        Lastname_var.setBackground(new java.awt.Color(255, 255, 255));
        Lastname_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username:");

        jLabel8.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email-Id:");

        jLabel9.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone no:");

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password:");

        jLabel11.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Country:");

        User_id_var.setBackground(new java.awt.Color(255, 255, 255));
        User_id_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Email_var.setBackground(new java.awt.Color(255, 255, 255));
        Email_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PhoneNo_var.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNo_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PhoneNo_var.setForeground(new java.awt.Color(0, 0, 0));
        PhoneNo_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNo_varActionPerformed(evt);
            }
        });

        Country_var.setBackground(new java.awt.Color(255, 255, 255));
        Country_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Country_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Country_varActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(208, 173, 252));
        jButton1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jButton1.setText("< Previous page");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submit_signup_btn.setBackground(new java.awt.Color(208, 173, 252));
        submit_signup_btn.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        submit_signup_btn.setText("Signup");
        submit_signup_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        submit_signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_signup_btnActionPerformed(evt);
            }
        });

        Confirmpassword_var.setBackground(new java.awt.Color(255, 255, 255));
        Confirmpassword_var.setForeground(new java.awt.Color(0, 0, 0));
        Confirmpassword_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmpassword_varActionPerformed(evt);
            }
        });

        password_var.setBackground(new java.awt.Color(255, 255, 255));
        password_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_varActionPerformed(evt);
            }
        });

        Gender_cb.setBackground(new java.awt.Color(204, 204, 204));
        Gender_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female", "Others" }));

        DOB_dc.setBackground(new java.awt.Color(31, 27, 36));
        DOB_dc.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FirstName_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(User_id_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lastname_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Email_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Confirmpassword_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(717, 717, 717)
                        .addComponent(submit_signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DOB_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneNo_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Country_var, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gender_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName_var, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(User_id_var, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Lastname_var, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Email_var, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(PhoneNo_var, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOB_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Gender_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmpassword_var, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Country_var, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addComponent(submit_signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Country_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Country_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Country_varActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Intpage().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submit_signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_signup_btnActionPerformed
                String first_name = FirstName_var.getText();
        String last_name = Lastname_var.getText();
        String email = Email_var.getText();
        String country = Country_var.getText();
        String phone_no = PhoneNo_var.getText();
        String password = password_var.getText();
        String confirm_password = Confirmpassword_var.getText();
        String gender = Gender_cb.getItemAt(Gender_cb.getSelectedIndex());
        Date dob = DOB_dc.getDate();
        String user_id = User_id_var.getText();
        
        if (first_name.trim().equals("")||
            last_name.trim().equals("")||
            email.trim().equals("")||
            country.trim().equals("")||
            password.trim().equals("")||
            confirm_password.trim().equals("")||
            phone_no.trim().equals("")||
            gender.trim().equals("Select...")||
            user_id.trim().equals("")) {
            JOptionPane.showMessageDialog(null,"All fields are compulsary...please check missing fields!!");
            if(isValid(email)==false){
               JOptionPane.showMessageDialog(null,"please enter valid email");

            }
           
        }else if(password.equals(confirm_password)){
            if(dob==null){
                JOptionPane.showMessageDialog(null, "Please enter date of birth");
                DOB_dc.grabFocus();
            }else{
                 if(passValid(password)==false){
                JOptionPane.showMessageDialog(null, "Invalid Password :\n" +
                                                                           "- minimum 8 or more characters\n" +
                                                                           "- one or more uppercase characters\n" +
                                                                           "- one or more lowercase characters\n" +
                                                                           "- one or more digits\n" +
                                                                           "- one or more special characters (like $, @, or !)");
            }else if(phValid(phone_no)==false){
                JOptionPane.showMessageDialog(null,"invalid phone Number");
            }else{
              ///main code
              //chicking email reg
                try {
                        Connection con = (Connection) myc.getConn();
                        String checkemail = "select first_name from account where email=?";
                        PreparedStatement pat = con.prepareStatement(checkemail);
                        pat.setString(1, email);
                        ResultSet rs=pat.executeQuery();
                        
                            if(rs.next()){
                                JOptionPane.showMessageDialog(null, "This ("+email+") Email is already taken!!");
                                Email_var.setText("");
                                Email_var.grabFocus();
                            }else{
                                String saveQry = "insert into account(first_name, last_name, password, email, country, gender, phone_no, dob,user_id) values(?,?,?,?,?,?,?,?,?)";
                                pat = con.prepareStatement(saveQry);
                                pat.setString(1, first_name);
                                pat.setString(2, last_name);
                                pat.setString(3, password);
                                pat.setString(4, email);
                                pat.setString(5, country);
                                pat.setString(6, gender);
                                pat.setString(7, phone_no);
                                
//                                SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yyyy");
//                                String dob1 = sdf.format(DOB_dc.getDate());
//                                System.out.println(DOB_dc.getDate());
                                
                                DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                      
                                String dob1 = dateFormat.format(DOB_dc.getDate());
                                System.out.println(gender);
                                pat.setString(8, dob1.toString());
                                pat.setString(9, user_id);
                                
                                int i = pat.executeUpdate();
                                if (i>=1) {
                                    JOptionPane.showMessageDialog(null,first_name+" "+last_name+" User Signup successful!!");
                                    new Signup().setVisible(true);
                                    this.setVisible(false);
                                }else{
                                    JOptionPane.showMessageDialog(null,first_name+" "+last_name+" User Signup Failed!!");
                                }
                            }
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,"User not inserted/saved exception : "+e);
                }
            }
                
               
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Password and Confirm Password must be same!!");
            password_var.setText("");
            Confirmpassword_var.setText("");
        }
    }//GEN-LAST:event_submit_signup_btnActionPerformed

    private void FirstName_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_varActionPerformed

    private void PhoneNo_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNo_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNo_varActionPerformed

    private void Confirmpassword_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmpassword_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirmpassword_varActionPerformed

    private void password_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_varActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginswap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginswap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginswap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginswap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Loginswap().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirmpassword_var;
    private javax.swing.JTextField Country_var;
    private com.toedter.calendar.JDateChooser DOB_dc;
    private javax.swing.JTextField Email_var;
    private javax.swing.JTextField FirstName_var;
    private javax.swing.JComboBox<String> Gender_cb;
    private javax.swing.JTextField Lastname_var;
    private javax.swing.JTextField PhoneNo_var;
    private javax.swing.JTextField User_id_var;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password_var;
    private javax.swing.JButton submit_signup_btn;
    // End of variables declaration//GEN-END:variables
}
