/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musiccataloguemasy;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nancy Merciline
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    MySQLConnect myc;
    public Signup() {
        initComponents();
        myc = new MySQLConnect();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PP1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        PP2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        PP3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        u_username_var = new javax.swing.JTextField();
        u_password_var = new javax.swing.JPasswordField();
        u_submit_var = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        e_email_var = new javax.swing.JTextField();
        e_password_var = new javax.swing.JPasswordField();
        e_submit_var = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p_phone_var = new javax.swing.JTextField();
        p_password_var = new javax.swing.JPasswordField();
        p_submit_var = new javax.swing.JButton();
        previouspage_btn_var = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(187, 134, 252));

        jPanel3.setBackground(new java.awt.Color(187, 134, 252));

        PP1.setBackground(new java.awt.Color(208, 173, 252));
        PP1.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        PP1.setText("Username");
        PP1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signup.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PP1mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Signup.this.mouseExited(evt);
            }
        });
        PP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(187, 134, 252));

        PP2.setBackground(new java.awt.Color(208, 173, 252));
        PP2.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        PP2.setText("Email-ID");
        PP2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signup.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PP1mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Signup.this.mouseExited(evt);
            }
        });
        PP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(187, 134, 252));

        PP3.setBackground(new java.awt.Color(208, 173, 252));
        PP3.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        PP3.setText("Phone no.");
        PP3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signup.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PP1mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Signup.this.mouseExited(evt);
            }
        });
        PP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jPanel6.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(31, 27, 36));
        p1.setForeground(new java.awt.Color(171, 85, 252));

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        u_username_var.setBackground(new java.awt.Color(204, 204, 204));
        u_username_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        u_username_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_username_varActionPerformed(evt);
            }
        });

        u_password_var.setBackground(new java.awt.Color(204, 204, 204));
        u_password_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        u_password_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_password_varActionPerformed(evt);
            }
        });

        u_submit_var.setBackground(new java.awt.Color(0, 204, 204));
        u_submit_var.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        u_submit_var.setText("Submit");
        u_submit_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        u_submit_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_submit_varActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 83, 251));
        jLabel10.setText("Login through Username");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(p1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(u_password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(42, 42, 42)
                                    .addComponent(u_username_var, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addComponent(u_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel10)
                .addGap(97, 97, 97)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_username_var, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(u_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel6.add(p1, "card2");

        p2.setBackground(new java.awt.Color(31, 27, 36));

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 85, 252));
        jLabel4.setText("Login through Email-ID");

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email-ID:");

        jLabel6.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");

        e_email_var.setBackground(new java.awt.Color(204, 204, 204));
        e_email_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        e_password_var.setBackground(new java.awt.Color(204, 204, 204));
        e_password_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        e_submit_var.setBackground(new java.awt.Color(0, 204, 204));
        e_submit_var.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        e_submit_var.setText("Submit");
        e_submit_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        e_submit_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_submit_varActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addComponent(e_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(e_password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(e_email_var, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(170, 170, 170))))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addGap(97, 97, 97)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_email_var, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(e_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel6.add(p2, "card3");

        p3.setBackground(new java.awt.Color(31, 27, 36));

        jLabel7.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 85, 252));
        jLabel7.setText("Login through Phone no.");

        jLabel8.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone no:");

        jLabel9.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");

        p_phone_var.setBackground(new java.awt.Color(204, 204, 204));
        p_phone_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        p_password_var.setBackground(new java.awt.Color(204, 204, 204));
        p_password_var.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        p_submit_var.setBackground(new java.awt.Color(0, 204, 204));
        p_submit_var.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        p_submit_var.setText("Submit");
        p_submit_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        p_submit_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_submit_varActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addGap(563, 565, Short.MAX_VALUE)
                .addComponent(p_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_phone_var, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(p_password_var, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7)
                .addGap(91, 91, 91)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_phone_var, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_password_var, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(p_submit_var, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel6.add(p3, "card4");

        previouspage_btn_var.setBackground(new java.awt.Color(153, 255, 255));
        previouspage_btn_var.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        previouspage_btn_var.setText("< previous page");
        previouspage_btn_var.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        previouspage_btn_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previouspage_btn_varActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previouspage_btn_var, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(previouspage_btn_var, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PP1ActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        if (evt.getSource()==PP1){
           p1.setVisible(true);
           p2.setVisible(false);
           p3.setVisible(false);
        }
        if (evt.getSource()==PP2){
           p1.setVisible(false);
           p2.setVisible(true);
           p3.setVisible(false);
        }
        if (evt.getSource()==PP3){
           p1.setVisible(false);
           p2.setVisible(false);
           p3.setVisible(true);
        }
    }//GEN-LAST:event_mouseClicked

    private void PP1mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PP1mouseEntered
        if (evt.getSource()==PP1){
        PP1.setBackground(new Color(204,204,255));
        }
        if (evt.getSource()==PP2){
        PP2.setBackground(new Color(204,204,255));
        }
        if (evt.getSource()==PP3){
        PP3.setBackground(new Color(204,204,255));
        }
    }//GEN-LAST:event_PP1mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
      if (evt.getSource()==PP1){
        PP1.setBackground(new Color(208,173,252));
        }
        if (evt.getSource()==PP2){
        PP2.setBackground(new Color(208,173,252));
        }
        if (evt.getSource()==PP3){
        PP3.setBackground(new Color(208,173,252));
        } 
    }//GEN-LAST:event_mouseExited

    private void previouspage_btn_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previouspage_btn_varActionPerformed
        new Intpage().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_previouspage_btn_varActionPerformed

    private void u_submit_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_submit_varActionPerformed
         String username = u_username_var.getText();
        String pass =u_password_var.getText();
        if(username.trim().equals("") || pass.trim().equals("")){
                JOptionPane.showMessageDialog(null, "All Fields are Compulsory!!");
        }else{
            try{
                    Connection con = (Connection) myc.getConn();
                    String sql = "select * from account where user_id=? and password=?" ;
                    PreparedStatement pst =  con.prepareStatement(sql);
                    pst.setString(1, username);
                    pst.setString(2, pass);
                    ResultSet rs = pst.executeQuery();
                    System.out.println(rs);
                    if(rs.next()){
                            JOptionPane.showMessageDialog(null, "Login Successful");
                            String UNAME = rs.getString("user_id");
                             new Homepage(UNAME).setVisible(true);
                             this.setVisible(false);
                    }else{
                            JOptionPane.showMessageDialog(null, "Incorrect username/Password!!!");
                    }
            
                    }catch(Exception e){
                        
                    }
        }
        
        

    }//GEN-LAST:event_u_submit_varActionPerformed

    private void PP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP2ActionPerformed
      
    }//GEN-LAST:event_PP2ActionPerformed

    private void PP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PP3ActionPerformed
     
    }//GEN-LAST:event_PP3ActionPerformed

    private void e_submit_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_submit_varActionPerformed
         String email = e_email_var.getText();
        String pass =e_password_var.getText();
        if(email.trim().equals("") || pass.trim().equals("")){
                JOptionPane.showMessageDialog(null, "All Fields are Compulsory!!");
        }else{
            try{
                    Connection con = (Connection) myc.getConn();
                    String sql = "select * from account where email=? and password=?" ;
                    PreparedStatement pst =  con.prepareStatement(sql);
                    pst.setString(1, email);
                    pst.setString(2, pass);
                    ResultSet rs = pst.executeQuery();
                    if(rs.next()){
                            JOptionPane.showMessageDialog(null, "Login Successful");
                            String UNAME = rs.getString("user_id");
                             new Homepage(UNAME).setVisible(true);
                             this.setVisible(false);
                    }else{
                            JOptionPane.showMessageDialog(null, "Incorrect email/Password!!!");
                    }
            
                    }catch(Exception e){
                        
                    }
        }
    }//GEN-LAST:event_e_submit_varActionPerformed

    private void p_submit_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_submit_varActionPerformed
        String phone = p_phone_var.getText();
        String pass =p_password_var.getText();
        if(phone.trim().equals("") || pass.trim().equals("")){
                JOptionPane.showMessageDialog(null, "All Fields are Compulsory!!");
        }else{
            try{
                    Connection con = (Connection) myc.getConn();
                    String sql = "select * from account where phone_no=? and password=?" ;
                    PreparedStatement pst =  con.prepareStatement(sql);
                    pst.setString(1, phone);
                    pst.setString(2, pass);
                    ResultSet rs = pst.executeQuery();
                    if(rs.next()){
                            JOptionPane.showMessageDialog(null, "Login Successful");
                            String UNAME = rs.getString("user_id");
                             new Homepage(UNAME).setVisible(true);
                             this.setVisible(false);
                    }else{
                            JOptionPane.showMessageDialog(null, "Incorrect phone no/Password!!!");
                    }
            
                    }catch(Exception e){
                        
                    }
        }
    }//GEN-LAST:event_p_submit_varActionPerformed

    private void u_username_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_username_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_username_varActionPerformed

    private void u_password_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_password_varActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_password_varActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PP1;
    private javax.swing.JButton PP2;
    private javax.swing.JButton PP3;
    private javax.swing.JTextField e_email_var;
    private javax.swing.JPasswordField e_password_var;
    private javax.swing.JButton e_submit_var;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPasswordField p_password_var;
    private javax.swing.JTextField p_phone_var;
    private javax.swing.JButton p_submit_var;
    private javax.swing.JButton previouspage_btn_var;
    private javax.swing.JPasswordField u_password_var;
    private javax.swing.JButton u_submit_var;
    private javax.swing.JTextField u_username_var;
    // End of variables declaration//GEN-END:variables
}
